use_frameworks!

target 'IrohaExample' do
    pod 'IrohaCommunication', :git => 'https://github.com/hyperledger/iroha-ios'
end

target 'IntegrationTestHost' do
    pod 'IrohaCommunication', :git => 'https://github.com/hyperledger/iroha-ios'

    target 'UnitTests' do
        inherit! :search_paths
    end

    target 'IntegrationTests' do
        inherit! :search_paths
    end
end
